<?php
/* 
 * options page framework generated by: http://wpsettingsapi.jeroensormani.com/
 *
 */
add_action( 'admin_menu', 'vd_add_admin_menu' );
add_action( 'admin_init', 'vd_settings_init' );


function vd_add_admin_menu(  ) { 

	add_options_page( 'Vimeo Downloads', 'Vimeo Downloads', 'manage_options', 'vimeo_downloads', 'vd_options_page' );

}


function vd_settings_init(  ) { 

	register_setting( 'pluginPage', 'vd_settings' );

	add_settings_section(
		'vd_pluginPage_section', 
		__( 'Your section description', 'wordpress' ), 
		'vd_settings_section_callback', 
		'pluginPage'
	);

	add_settings_field( 
		'vd_text_field_0', 
		__( 'Settings field description', 'wordpress' ), 
		'vd_text_field_0_render', 
		'pluginPage', 
		'vd_pluginPage_section' 
	);

	add_settings_field( 
		'vd_text_field_1', 
		__( 'Settings field description', 'wordpress' ), 
		'vd_text_field_1_render', 
		'pluginPage', 
		'vd_pluginPage_section' 
	);

	add_settings_field( 
		'vd_text_field_2', 
		__( 'Settings field description', 'wordpress' ), 
		'vd_text_field_2_render', 
		'pluginPage', 
		'vd_pluginPage_section' 
	);

	add_settings_field( 
		'vd_textarea_field_3', 
		__( 'Settings field description', 'wordpress' ), 
		'vd_textarea_field_3_render', 
		'pluginPage', 
		'vd_pluginPage_section' 
	);


}


function vd_text_field_0_render(  ) { 

	$options = get_option( 'vd_settings' );
	?>
	<input type='text' name='vd_settings[vd_text_field_0]' value='<?php echo $options['vd_text_field_0']; ?>'>
	<?php

}


function vd_text_field_1_render(  ) { 

	$options = get_option( 'vd_settings' );
	?>
	<input type='text' name='vd_settings[vd_text_field_1]' value='<?php echo $options['vd_text_field_1']; ?>'>
	<?php

}


function vd_text_field_2_render(  ) { 

	$options = get_option( 'vd_settings' );
	?>
	<input type='text' name='vd_settings[vd_text_field_2]' value='<?php echo $options['vd_text_field_2']; ?>'>
	<?php

}


function vd_textarea_field_3_render(  ) { 

	$options = get_option( 'vd_settings' );
	?>
	<textarea cols='40' rows='5' name='vd_settings[vd_textarea_field_3]'> 
		<?php echo $options['vd_textarea_field_3']; ?>
 	</textarea>
	<?php

}


function vd_settings_section_callback(  ) { 

	echo __( 'This section description', 'wordpress' );

}


function vd_options_page(  ) { 

	?>
	<form action='options.php' method='post'>
		
		<h2>Vimeo Downloads</h2>
		
		<?php
		settings_fields( 'pluginPage' );
		do_settings_sections( 'pluginPage' );
		submit_button();
		?>
		
	</form>
	<?php

}

?>